### ISSUE TITLE
Footer disappears behind cat image

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/animal-rescue-website#1]
Can't figure out why the footer has disappeared behind the cat - help! @charlie-quinn

-Brianna

**Comment by charlie-quinn** [comment]
I'll take a look at this later tonight. 👀

**Comment by charlie-quinn** [comment]
- [ ] remove the `absolute` class from the container holding the last cat image before the footer
- [ ] make the cat img a background image on this container holding the text, [something like this](https://share.getcloudapp.com/o0uQp5QB)
- [ ] also [add some padding to the container](https://share.getcloudapp.com/X6uDrmDm)

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
