### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/animal-rescue-website#2]
@charlie-quinn

I did the best that I could with the time I had available for this website. Everything is up and running, but I didn't have the time to add in all the accessibility things that I wanted to get in there. If I would have had more time I also would have paid more attention to the sizing of headers and whatnot. Most of the required content has been included, but there are speed and accessibility issues. I definitely could have done a better job. For these reasons, I think I deserve a C+ or B-.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
