### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/animal-rescue-website#3]
@charlie-quinn
https://docs.google.com/spreadsheets/d/1v3nvFa_IU4d6-2FTpGnNv6KMnDm3bDWJZ1AaTQTjEpo/edit?usp=sharing

Filled out what I could with the coding that I actually had.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
